name: Test and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build and start Docker services
        run: |
          export DOCKER_BUILDKIT=1
          docker compose -f docker-compose.ci.yml up -d --build

      - name: Check code style with Pint
        run: docker compose -f docker-compose.ci.yml exec -T --user root app composer lint:check

      - name: Run static analysis with Larastan
        run: docker compose -f docker-compose.ci.yml exec -T --user root app composer analyse

      - name: Run Pest tests
        run: docker compose -f docker-compose.ci.yml exec -T --user root app composer test

      - name: Stop Docker services
        if: always()
        run: docker compose -f docker-compose.ci.yml down

  publish:
    needs: test

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v5

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
